### ISSUE TITLE
Great package ! Any word on JWT or Amazon S3 support?

### ISSUE THREAD

**Issue by siredwin** [xyproto/permissions2#14]
First of all, thank you. This is a great package indeed that works very well with Echo. I have tried a few but i am sticking with this one for now.
 I have a few questions concerning this package that could help me better implement it and clarify some things.
 

- Why Redis database? It would only make sense if there was a way to make data persistent. I tried to look and see if that is the case but i was confused. Is the data persistent? I can testify that it is truly efficient and fast but i also want to save as much RAM/memory for my real program.

- Bolt database stores data in the root directory in a file! To me that sounds  a bit risky. Is that by design?

- Also, bolt almost looks and works like Amazon S3. Would you mind supporting that in the future for folks like me that would rather save everything in a  cloud key/value storage?

- About JWT -- I can actually incorporate that but your package seems to almost implement things the same way. Am i losing anything by not using JWT vs cookies?

Regards.

**Comment by xyproto** [comment]
Hi, thanks for the feedback! I'm glad you like and use `permissions2`. I'll try my best to answer:

## Redis

`permissions2` uses Redis mainly because I know a lot of work has gone into selecting the best algorithms for each Redis command by its author. Also, it's very fast and scalable. It can be configured to be persistant or not, depending on your needs. If you want something else, [pstore](https://github.com/xyproto/pstore) (using PostgreSQL), [permissionbolt](https://github.com/xyproto/permissionbolt) (using BoltDB) or [permissionsql](https://github.com/xyproto/permissionsql) might work for you. PostgreSQL might be the best option if you are most conserned with persistence, while BoltDB should have a small memory footprint (and requires no external server).

## BoltDB

When creating a new `Permissions` struct with `permissionbolt`, you can use `NewWithConf` instead of `New`, to specify any filename you like. Example:

```go
perm, err := permissionbolt.NewWithConf("/var/my.db")
```

BoltDB is [ACID](https://en.wikipedia.org/wiki/ACID) compliant (just like SQLite). There should be nothing particularly unsafe or risky about BoltDB. I think testing it in production in several companies over several years is the only way to know for sure, for any database. To me, both the code and behavior of BoltDB looks sane, clean and solid.

## S3

I will consider creating a `permissions`-like package for S3, thanks for the suggestion.

## JWT and cookies

When it comes to JWT, I am still on the fence and still learning about it. I think it's worrysome that articles like [this one](https://news.ycombinator.com/item?id=13865459) pop up with regular intervals, suggesting JWT should not be used. I will have to read up on it. While cookies are not particularly elegant, they are well tested. Something like JWT, Oauth1, Oauth2 or Kerberos might be better, but it completely depends on what you need and want, and what your users can tolerate.

Cheers!

**Comment by siredwin** [comment]
Thanks.  
Just one more thing.  I was creating users and i realized that there is no unique field other that probably the id of the db entry.  That means that a user can create many usernames with the  same email over and over again.  I think it would be a nice idea if there was a function that checks if valid email (regardless of username) exists already. That way email becomes unique field as i think it should be. One unique email per user.

**Comment by xyproto** [comment]
Good suggestion, I will consider adding functionality for having unique email addresses.

**Comment by siredwin** [comment]
Here is my quick implementation of checking email if exists. Let me know what you think

    //CheckExistEmail : checks to see if given email exists
    func CheckExistEmail(newEmail string) (bool, error){
        allUsers, _ := userstate.AllUsernames()
        for _, username :=range allUsers{
		email, err := userstate.Email(username)
		if err != nil {
			log.Println(err)
			return false, err
		}

		if email == newEmail{
			return true, nil
	        }
        }
        return false, nil
    }

**Comment by xyproto** [comment]
Thank you for the suggestion. I implemented something similar, with the function name `HasEmail`.

**Comment by siredwin** [comment]
Thanks. I already implemented that but it is always better coming from the package
