### ISSUE TITLE
Mysql support

### ISSUE THREAD

**Issue by Xwi** [xyproto/permissions2#2]
There MYSQL support plan?

**Comment by PascalLeMerrer** [comment]
Hi
Do you have any idea of a possible release date for permission 3?

**Comment by xyproto** [comment]
No specific estimates and I don't really see why MySQL (or MariaDB, or PostgreSQL) would be attractive to use over Redis. In addition to this, supporting Redis and SQL databases at the same time clutters the current way of doing things. But I'm giving it a shot, for the sake of feature completion.

Perhaps a month or two from now.

**Comment by nkev** [comment]
> ...supporting Redis and SQL databases at the same time clutters the current way of doing things...

Exactly! Since most people use a MySQL or PostreSQL database, they don't necessarily want to also install Redis :)

**Comment by xyproto** [comment]
I have now tried a few different attempts/approaches at combining redis and sql by using interfaces, but this only seems to make the code messy, because of the differences between Redis and SQL databases. I think I'll rather create a separate project for permissions2, under a different name, that uses SQL databases instead.

**Comment by xyproto** [comment]
Ok. Created https://github.com/xyproto/permissionsql for supporting MariaDB/MySQL. All tests pass here.
