### ISSUE TITLE
Database Migration.

### ISSUE THREAD

**Issue by siredwin** [xyproto/permissions2#25]
It has been great using this package for the last 4 or more years. 
I would like to migrate to a more robust user management system.
Would you be able to help me understand the database setup?
We can email privately if this is a security issue.
Thanks.

**Comment by xyproto** [comment]
Hi @siredwin. It warms my soul that you've used `permissions2` for 4+ years.

I would be happy to help out both in making the user management system more robust and/or with details about the database setup. I can't think of any potential security issues with discussing this here, since all the code is also open source and readily reviewable by anyone.

`permissions2` uses Redis in the most straightforward way I could think of, which is a hash map of where the username is the key:
https://github.com/xyproto/permissions2/blob/main/userstate.go#L162

To be able to quickly index all the keys, there is also a list of all the usernames:
https://github.com/xyproto/permissions2/blob/main/userstate.go#L165

Then, there is also a list of users that have registered, but are not yet confirmed (by, say, clicking an e-mail link):
https://github.com/xyproto/permissions2/blob/main/userstate.go#L168

In order to store a username together with other properties, like for instance `prefersDarkMode=true`, the username + the key for the property are used as the hash map key, and "true" for the value. For example, for the user bob:

* Redis hash map key: `bob:prefersDarkMode`
* Redis hash map value: `true`

The layer between Redis and `permissions2` is the `simpleredis` package. That is where the `:` between the two keys comes from. Here is the implementation of the HashMap, which uses the `HSET` command in Redis:

https://github.com/xyproto/simpleredis/blob/main/simpleredis.go#L447

Given a username, like `bob` as the "elementid" parameter, this function can be used for listing all the property keys:

https://github.com/xyproto/simpleredis/blob/main/simpleredis.go#L508

Redis is more robust than people generally first have the impression of, though, and has settings for persisting data to disk. It's not only a database for storing data in memory. I would be very interested in hearing about which types of robustness gains you are envisioning.
